languag: python
python:
  - "3.3"
  - "2.7"
  - "2.6"
  - "2.5"
install:
  - "pip install --user pyzmq --install-option=--zmq=bundled"
  - "pip install --user docopt"
script: "cd py; python zero.py test -v"
