languag: python
python:
  - "3.3"
  - "2.7"
  - "2.6"
  - "2.5"
install:
  - "pip install --egg --user --install-option=--prefix= docopt"
  - "pip install --egg --user --install-option=--zmq=bundled --install-option=--prefix= pyzmq"
script: "cd py; python zero.py test -v"
